version: '3.8'

services:
  db:
    image: postgres:15
    container_name: coffee_machine_db
    environment:
      POSTGRES_DB: coffee_machine
      POSTGRES_USER: springstudent
      POSTGRES_PASSWORD: springstudent
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - coffee-network

networks:
  coffee-network:

volumes:
  db_data:
